version: '3.8'

services:
  app:
    build: 
      context: ./docker/php
      dockerfile: php.Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - laravel
  
  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/src
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel
    
  db:
    image: mysql:8
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Appik
      MYSQL_USER: Appik
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel
    
  composer:
    image: composer:latest
    container_name: laravel_composer
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    command: ["composer" , "create-project" , "--prefer-dist",  "laravel/laravel","--force" , "."]
    networks:
      - laravel
   
networks:
  laravel:
volumes:
  db_data:
    

     